### ISSUE TITLE
Will Macbook pro kill the arduino with 5v voltage?

### ISSUE THREAD

**Issue by songproducer** [prof-groff/tezio#1]
Hi! This is is an interesting project and am considering getting an Arduino.
But I saw both Arduinos require 3.3v and will be damaged if receiving 5v. Do you know if USB-C to USB-A will work without needing any extra voltage regulation equipment?

**Comment by prof-groff** [comment]
Hi, glad you are interested.

No, the Arduino boards have voltage regulators to step 5 V USB to 3.3 V.

Jeff

Jeffrey R. Groff
Shepherd University
Professor of Physics
Chair, Department of Environmental and Physical Sciences
________________________________
From: Leo ***@***.***>
Sent: Wednesday, October 19, 2022 4:00 AM
To: prof-groff/tezio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [prof-groff/tezio] Will Macbook pro kill the arduino with 5v voltage? (Issue #1)


Hi! This is is an interesting project and am considering getting an Arduino.
But I saw both Arduinos require 3.3v and will be damaged if receiving 5v. Do you know if USB-C to USB-A will work without needing any extra voltage regulation equipment?
